#!/usr/bin/env python3
"""
Build the multimodal demo project: a Cu–Au alloy library seen by 15 techniques.

:func:`build_showcase_project` writes a complete, self-consistent campaign to
disk — authored metadata in three stages, raw files in the formats the
instruments would have written, and a deliberately incomplete measurement
matrix.  Everything in it follows from one hidden number per sample, the gold
atomic fraction, so every technique can be checked against every other.

What the project is *for*
-------------------------
It answers the question a new user actually has, which is not "what can this
package do" but "what would I do with my own campaign".  So it contains the
things a real campaign contains and a toy example usually leaves out:

* **two routes in** — measurements declared in metadata, and measurements that
  arrive as a folder someone dropped on the share;
* **three stages** — synthesis, characterization, testing — plus computation,
  because the DFT numbers belong with the sample too;
* **a sparse matrix** — beamtime-limited techniques are on four samples, not
  eight, which is what :meth:`Project.availability` is for;
* **a failed run** — one synthesis aborted and has no data, so the table has a
  row that must be excluded rather than being uniformly tidy;
* **techniques that disagree for a reason** — TEM and DLS report different
  sizes, EDS and XPS report different compositions, and both disagreements are
  physics rather than error.

Nothing is committed to the repository: the project is generated on demand and
can be deleted freely.

>>> from NanoOrganizer.demo import build_showcase_project
>>> root = build_showcase_project("/tmp/CuAuDemo")       # doctest: +SKIP
>>> from NanoOrganizer import open_project               # doctest: +SKIP
>>> wb = open_project(root)                              # doctest: +SKIP
"""

from __future__ import annotations

import pprint
import shutil
from pathlib import Path
from typing import Any, Dict, List, Sequence

import numpy as np

from NanoOrganizer.demo import images as img
from NanoOrganizer.demo import materials as mat
from NanoOrganizer.demo import signals as sig

#: Marker file proving a directory was made here, so a rebuild can never
#: delete somebody's real data.
MARKER = ".nanoorganizer-demo"

#: Campaign label written into every stage.
CAMPAIGN = "CuAu-CO2RR"


# ---------------------------------------------------------------------------
# Small writers
# ---------------------------------------------------------------------------

def _write_curve(path: Path, x: np.ndarray, y: np.ndarray,
                 x_label: str, y_label: str, note: str = "") -> str:
    """Write a two-column text file with a self-describing header."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = f"{x_label}\t{y_label}"
    if note:
        header = f"{note}\n{header}"
    np.savetxt(path, np.column_stack([np.asarray(x), np.asarray(y)]),
               fmt="%.6g", delimiter="\t", header=header)
    return str(path)


def _clean(value: Any) -> Any:
    """Make a value safe to write into a Python source file."""
    if isinstance(value, (np.floating, np.integer)):
        return value.item()
    if isinstance(value, dict):
        return {k: _clean(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_clean(v) for v in value]
    return value


_MODULE_HEADER = '''"""{title}

Generated by ``NanoOrganizer.demo.build_showcase_project`` — edit the
generator, not this file.

The shape is the one the ``sampledict`` ingest adapter expects: a module-level
dict keyed by stable sample ids, each holding nested blocks.  A block that
names files becomes a measurement; every other block is kept verbatim as
filterable parameters.  The dict's own name gives the stage.
"""

'''


def _write_metadata(path: Path, dict_name: str, title: str,
                    records: Dict[str, Dict]) -> None:
    body = pprint.pformat(_clean(records), width=76, sort_dicts=False)
    path.write_text(_MODULE_HEADER.format(title=title)
                    + f"{dict_name} = {body}\n")


# ---------------------------------------------------------------------------
# Per-sample data
# ---------------------------------------------------------------------------

def _write_uvvis(folder: Path, tag: str, x: float, n_frames: int,
                 rng) -> List[str]:
    """In-situ growth series: one single-column frame per time point."""
    folder.mkdir(parents=True, exist_ok=True)
    written = []
    for time_s, temperature_C, values in sig.uvvis_frames(x, n_frames, rng):
        name = f"uvvis_{tag}_t{int(time_s):05d}s_T{temperature_C:.0f}C.npy"
        np.save(folder / name, values)
        written.append(name)
    return written


def _write_spectroscopy(folder: Path, index: int, x: float, rng) -> Dict[str, Any]:
    """EDS, XPS, Raman, IR and (for some samples) XAS."""
    out: Dict[str, Any] = {}

    energy, counts = sig.eds_spectrum(x, rng)
    out["eds"] = _write_curve(folder / "eds.dat", energy, counts,
                              "energy_keV", "counts",
                              "EDS, 20 kV, silicon drift detector")

    binding, counts = sig.xps_cu2p(x, rng)
    out["xps_cu2p"] = _write_curve(folder / "xps_Cu2p.dat", binding, counts,
                                   "binding_energy_eV", "counts",
                                   "XPS Cu 2p, Al Ka, pass energy 20 eV")
    binding, counts = sig.xps_au4f(x, rng)
    out["xps_au4f"] = _write_curve(folder / "xps_Au4f.dat", binding, counts,
                                   "binding_energy_eV", "counts",
                                   "XPS Au 4f, Al Ka, pass energy 20 eV")

    shift, intensity = sig.raman_spectrum(x, rng)
    out["raman"] = _write_curve(folder / "raman.dat", shift, intensity,
                                "raman_shift_cm-1", "intensity_counts",
                                "Raman, 633 nm, 1 mW, 30 s")

    wavenumber, absorbance = sig.ir_spectrum(x, rng)
    out["ir"] = _write_curve(folder / "ir_seira.dat", wavenumber, absorbance,
                             "wavenumber_cm-1", "absorbance",
                             "ATR-SEIRAS at -1.0 V vs RHE, CO2-saturated")

    if mat.measured("xas", index):
        for state, label in (("as_made", "as-made"), ("reduced", "after 1 h at -1.0 V")):
            energy, mu = sig.xas_spectrum(x, state, rng)
            out[f"xas_{state}"] = _write_curve(
                folder / f"xas_Cu_K_{state}.dat", energy, mu,
                "energy_eV", "normalised_mu", f"Cu K-edge XANES, {label}")
    return out


def _write_scattering(folder: Path, index: int, x: float, rng) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    q, intensity = sig.saxs_curve(x, rng)
    out["saxs"] = _write_curve(folder / "saxs_1d.dat", q, intensity,
                               "q_invA", "I_q_a.u.",
                               "SAXS, 13.5 keV, 2 m, azimuthally averaged")

    q, intensity = sig.waxs_curve(x, rng)
    out["waxs"] = _write_curve(folder / "waxs_1d.dat", q, intensity,
                               "q_invA", "I_q_a.u.",
                               "WAXS, 13.5 keV, 0.2 m, azimuthally averaged")

    if mat.measured("saxs2d", index):
        names = []
        for frame in range(2):
            pattern = img.saxs2d_pattern(x, 256, rng)
            name = f"saxs2d_{frame:03d}.npy"
            np.save(folder / name, pattern.astype(np.float32))
            names.append(str(folder / name))
        out["saxs2d"] = names
    return out


def _write_electrochemistry(folder: Path, x: float, rng) -> Dict[str, Any]:
    out: Dict[str, Any] = {}

    potential, current = sig.her_lsv(x, rng)
    out["her"] = _write_curve(folder / "her_lsv.dat", potential, current,
                              "potential_V_vs_RHE", "j_mA_cm2",
                              "LSV, Ar-saturated 0.1 M KHCO3, 5 mV/s, iR-corrected")

    potential, current = sig.oer_lsv(x, rng)
    out["oer"] = _write_curve(folder / "oer_lsv.dat", potential, current,
                              "potential_V_vs_RHE", "j_mA_cm2",
                              "LSV, 1 M KOH, 5 mV/s, anodically conditioned film")

    potential, current = sig.co2rr_lsv(x, rng)
    out["co2rr_lsv"] = _write_curve(folder / "co2rr_lsv.dat", potential, current,
                                    "potential_V_vs_RHE", "j_mA_cm2",
                                    "LSV, CO2-saturated 0.1 M KHCO3, 5 mV/s")

    efficiencies = sig.co2rr_faradaic(x, rng)
    files = []
    for product, (potentials, values) in efficiencies.items():
        safe = product.replace("-", "").replace("+", "")
        files.append(_write_curve(
            folder / f"FE_{safe}.dat", potentials, values,
            "potential_V_vs_RHE", "faradaic_efficiency_pct",
            f"{product} by GC/HPLC, 1 h chronoamperometry per point"))
    out["fe_files"] = files
    return out


# ---------------------------------------------------------------------------
# Records
# ---------------------------------------------------------------------------

def _synthesis_record(index: int, x: float) -> Dict[str, Any]:
    total_uL = 900.0
    return {
        "sample_id": mat.sample_id(index),
        "synthesis_batch": {
            "run_id": f"cuau_run_{index:02d}",
            "batch_tag": f"library_{(index - 1) // 4 + 1}",
            "campaign": CAMPAIGN,
            "status": "done",
            "aborted": False,
            "started_at": f"2026-04-{index + 2:02d}T09:30:00",
            "run_time_s": 5400.0,
        },
        "composition": {
            "nominal_x_Au": round(float(x), 3),
            "metal_total_umol": 20.0,
            "alloy": "CuAu",
        },
        "reagents": {
            "HAuCl4": {"concentration_mM": 10.0,
                       "volume_uL": round(total_uL * x, 1)},
            "Cu_acetate": {"concentration_mM": 10.0,
                           "volume_uL": round(total_uL * (1.0 - x), 1)},
            "oleylamine_uL": 2000.0,
            "borane_tBu_amine_mg": 35.0,
        },
        "conditions": {
            "temperature_C": 150.0,
            "hold_time_min": 60.0,
            "atmosphere": "N2",
            "stir_rate_rpm": 600,
        },
        "support": {"material": "Vulcan XC-72", "loading_wt_pct": 20.0},
    }


def _characterization_record(index: int, x: float, paths: Dict[str, Any],
                             n_frames: int) -> Dict[str, Any]:
    record: Dict[str, Any] = {
        "sample_id": mat.sample_id(index),
        "characterization_batch": {
            "run_id": f"char_{index:02d}",
            "batch_tag": f"library_{(index - 1) // 4 + 1}",
            "campaign": CAMPAIGN,
            "status": "done",
            "started_at": f"2026-04-{index + 3:02d}T11:00:00",
        },
        "UVVis": {
            "modality": "uvvis",
            "instrument": "DemoSpec HR4000",
            "note": "in-situ growth series; the last frame is the product",
            "n_frames": n_frames,
            "path_length_mm": 10.0,
            "spectrum_glob": paths["uvvis_glob"],
            "wavelength_file": paths["uvvis_axis"],
        },
        "EDS": {
            "modality": "eds",
            "instrument": "DemoSEM + 100 mm2 SDD",
            "beam_energy_keV": 20.0,
            "quantification": "Cliff-Lorimer",
            "k_factor_Au_La_over_Cu_Ka": sig.EDS_K_FACTOR_AU_CU,
            "note": "bulk composition; compare with XPS, which sees the surface",
            "files": [paths["eds"]],
        },
        "XPS_Cu2p": {
            "modality": "xps", "instrument": "DemoXPS",
            "source": "Al Ka 1486.6 eV", "pass_energy_eV": 20.0,
            "sensitivity_factor": sig.XPS_RSF["Cu 2p3/2"],
            "note": "the satellite near 942 eV is Cu(II)",
            "files": [paths["xps_cu2p"]],
        },
        "XPS_Au4f": {
            "modality": "xps", "instrument": "DemoXPS",
            "source": "Al Ka 1486.6 eV", "pass_energy_eV": 20.0,
            "sensitivity_factor": sig.XPS_RSF["Au 4f7/2"],
            "files": [paths["xps_au4f"]],
        },
        "Raman": {
            "modality": "raman", "instrument": "DemoRaman",
            "laser_nm": 633.0, "power_mW": 1.0, "integration_s": 30.0,
            "note": "Cu2O phonons below 700 cm-1; carbon D and G from the support",
            "files": [paths["raman"]],
        },
        "IR": {
            "modality": "ir", "instrument": "DemoFTIR, ATR-SEIRAS cell",
            "potential_V_vs_RHE": mat.REPORT_POTENTIAL_V,
            "resolution_cm1": 4.0,
            "note": "the band near 2100 cm-1 is CO adsorbed atop a metal site",
            "files": [paths["ir"]],
        },
        "SAXS": {
            "modality": "saxs1d", "instrument": "DemoBeamline",
            "energy_keV": 13.5, "distance_m": 2.0,
            "note": "size from Guinier; same particles the micrographs show",
            "files": [paths["saxs"]],
        },
        "WAXS": {
            "modality": "waxs1d", "instrument": "DemoBeamline",
            "energy_keV": 13.5, "distance_m": 0.2,
            "note": "fcc; q_hkl = 2*pi*sqrt(h2+k2+l2)/a gives the lattice parameter",
            "files": [paths["waxs"]],
        },
    }

    if "saxs2d" in paths:
        record["SAXS2D"] = {
            "modality": "saxs2d", "instrument": "DemoBeamline, Pilatus 300k",
            "energy_keV": 13.5, "distance_m": 2.0,
            "beam_centre_px": [128, 128], "pixel_size_mm": 0.172,
            "note": "the detector image the 1D curve was averaged from",
            "files": paths["saxs2d"],
        }

    if "xas_as_made" in paths:
        record["XAS_as_made"] = {
            "modality": "xas", "instrument": "DemoBeamline, Si(111)",
            "edge": "Cu K", "edge_energy_eV": 8979.0, "mode": "fluorescence",
            "state": "as-made",
            "files": [paths["xas_as_made"]],
        }
        record["XAS_after_reaction"] = {
            "modality": "xas", "instrument": "DemoBeamline, Si(111)",
            "edge": "Cu K", "edge_energy_eV": 8979.0, "mode": "fluorescence",
            "state": "after 1 h at -1.0 V vs RHE",
            "note": "the edge returns to metallic; this is the active phase",
            "files": [paths["xas_reduced"]],
        }

    if "xpcs" in paths:
        record["XPCS"] = {
            "modality": "xpcs_g2", "instrument": "DemoBeamline, coherent branch",
            "q_invA": sig.XPCS_Q_INV_A,
            "viscosity_Pa_s": sig.XPCS_VISCOSITY_Pa_s,
            "temperature_K": 298.0,
            "note": "aggregates in glycerol/water; the decay rate is D*q^2",
            "files": [paths["xpcs"]],
        }
    return record


def _testing_record(index: int, x: float, paths: Dict[str, Any]) -> Dict[str, Any]:
    efficiency = mat.faradaic_efficiency(x)
    return {
        "sample_id": mat.sample_id(index),
        "testing_batch": {
            "run_id": f"ec_{index:02d}",
            "batch_tag": f"library_{(index - 1) // 4 + 1}",
            "campaign": CAMPAIGN,
            "status": "done",
            "started_at": f"2026-05-{index:02d}T08:00:00",
        },
        "cell": {
            "type": "flow cell, gas diffusion electrode",
            "electrolyte": "0.1 M KHCO3",
            "membrane": "Selemion AMV",
            "catalyst_loading_mg_cm2": 0.5,
            "reference": "leak-free Ag/AgCl",
        },
        "performance": {
            "report_potential_V_vs_RHE": mat.REPORT_POTENTIAL_V,
            "current_density_mA_cm2": round(mat.current_density(x), 2),
            "FE_CO_pct": round(efficiency["CO"], 1),
            "FE_H2_pct": round(efficiency["H2"], 1),
            "FE_C2H4_pct": round(efficiency["C2H4"], 1),
            "FE_HCOO_pct": round(efficiency["HCOO-"], 1),
            "j_CO_mA_cm2": round(mat.co_partial_current(x), 2),
            "her_tafel_mV_dec": round(mat.her_tafel_mV(x), 0),
            "oer_overpotential_mV": round(mat.oer_overpotential_mV(x), 0),
        },
        "HER_LSV": {
            "modality": "ec", "technique": "LSV",
            "atmosphere": "Ar", "scan_rate_mV_s": 5.0,
            "note": "the competing reaction, measured without CO2",
            "files": [paths["her"]],
        },
        "OER_LSV": {
            "modality": "ec", "technique": "LSV",
            "electrolyte": "1 M KOH", "scan_rate_mV_s": 5.0,
            "note": "weak trend; the material is a mediocre OER catalyst either way",
            "files": [paths["oer"]],
        },
        "CO2RR_LSV": {
            "modality": "ec", "technique": "LSV",
            "atmosphere": "CO2", "scan_rate_mV_s": 5.0,
            "files": [paths["co2rr_lsv"]],
        },
        "CO2RR_FE": {
            "modality": "ec", "technique": "chronoamperometry + GC/HPLC",
            "atmosphere": "CO2", "hold_time_min": 60.0,
            "products": list(mat.PRODUCTS),
            "note": "one file per product; they sum to 100 % at every potential",
            "files": paths["fe_files"],
        },
    }


def _computation_record(index: int, x: float, pdos_path: str) -> Dict[str, Any]:
    return {
        "sample_id": mat.sample_id(index),
        "computation_batch": {
            "run_id": f"dft_{index:02d}",
            "campaign": CAMPAIGN,
            "status": "done",
            "started_at": f"2026-05-1{index % 10}T00:00:00",
        },
        "setup": {
            "code": "plane-wave DFT (synthetic)",
            "functional": "RPBE",
            "plane_wave_cutoff_eV": 500.0,
            "k_points": "4x4x1",
            "slab": "(211) step, 4 layers, bottom two fixed",
            "vacuum_A": 15.0,
        },
        "descriptors": {
            "d_band_centre_eV": round(mat.d_band_centre_eV(x), 3),
            "E_ads_CO_eV": round(mat.co_binding_eV(x), 3),
            "E_ads_H_eV": round(mat.h_binding_eV(x), 3),
            "note": ("CO binding is the descriptor: too strong and CO never "
                     "leaves, too weak and it leaves before it can couple"),
        },
        "PDOS": {
            "modality": "dos",
            "projection": "surface-layer d states",
            "note": "the centroid of this band is the d-band centre",
            "files": [pdos_path],
        },
    }


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

def build_showcase_project(root, *,
                           fractions: Sequence[float] = mat.DEFAULT_FRACTIONS,
                           n_frames: int = 14,
                           n_micrographs: int = 3,
                           image_size: int = 384,
                           tomo_size: int = 128,
                           seed: int = 7,
                           with_images: bool = True,
                           with_tomography: bool = True,
                           include_failed_run: bool = True,
                           overwrite: bool = True) -> Path:
    """Write the multimodal demo project and return its root path.

    Parameters
    ----------
    root : path
        Where to write it.  Created if missing.
    fractions : sequence of float
        Gold atomic fraction of each sample — the hidden control variable.
        One sample is generated per entry.
    n_frames : int
        UV-Vis frames per sample, written as an in-situ growth series.
    n_micrographs : int
        TEM and SEM frames per sample.  ``with_images=False`` skips both, and
        the project then builds without Pillow.
    tomo_size : int
        Edge of the cubic tomogram in voxels.  This is the one large file in
        the project, so it is the first thing to turn down.
    include_failed_run : bool
        Append a synthesis that aborted and has no data at all.
    overwrite : bool
        Replace an existing demo project.  Only ever removes a directory
        carrying the generator's marker file, so pointing this at real data
        cannot delete it.
    """
    root = Path(root).expanduser()
    marker = root / MARKER

    if root.exists() and overwrite:
        if any(root.iterdir()) and not marker.exists():
            raise FileExistsError(
                f"{root} is not empty and was not made by "
                f"build_showcase_project. Choose another path, or delete it "
                f"yourself."
            )
        shutil.rmtree(root)

    root.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by NanoOrganizer.demo.build_showcase_project\n")

    rng = np.random.default_rng(seed)

    uvvis_root = root / "RawSpectra" / "uvvis_runs"
    uvvis_root.mkdir(parents=True, exist_ok=True)
    axis_path = uvvis_root / "axis_wavelength.npy"
    np.save(axis_path, sig.UVVIS_AXIS)

    synthesis: Dict[str, Dict] = {}
    characterization: Dict[str, Dict] = {}
    testing: Dict[str, Dict] = {}
    computation: Dict[str, Dict] = {}

    for index, x in enumerate(fractions, start=1):
        name = mat.sample_id(index)
        tag = f"b{index:02d}"
        paths: Dict[str, Any] = {}

        _write_uvvis(uvvis_root, tag, x, n_frames, rng)
        paths["uvvis_glob"] = str(uvvis_root / f"uvvis_{tag}_*.npy")
        paths["uvvis_axis"] = str(axis_path)

        paths.update(_write_spectroscopy(root / "Spectroscopy" / name, index, x, rng))
        paths.update(_write_scattering(root / "Scattering" / name, index, x, rng))

        if mat.measured("xpcs", index):
            lag, g2 = sig.xpcs_g2(x, rng)
            paths["xpcs"] = _write_curve(
                root / "Dynamics" / name / "xpcs_g2.dat", lag, g2,
                "lag_time_s", "g2", "XPCS, aggregates in glycerol/water")

        electro = _write_electrochemistry(root / "Electrochemistry" / name, x, rng)
        energy, dos = sig.dft_pdos(x)
        pdos_path = _write_curve(root / "Computation" / name / "pdos.dat",
                                 energy, dos, "E_minus_EF_eV",
                                 "states_per_eV_per_atom",
                                 "surface-layer projected DOS")

        # Folder-convention data: no metadata entry, picked up by the
        # <Modality>Data/<SampleID>/ rule.
        diameters = sig.dls_distribution(x, rng)
        _write_curve(root / "DLSData" / name / "dls_intensity.dat",
                     diameters[0], diameters[1], "diameter_nm", "intensity_pct",
                     "DLS, 173 deg backscatter, intensity-weighted")

        if with_images:
            for frame in range(1, n_micrographs + 1):
                img.write_tiff(root / "TEMData" / name / f"{frame:02d}.tif",
                               img.tem_image(x, image_size, rng),
                               img.TEM_PIXELS_PER_MICRON, "DemoTEM 200 kV")
                img.write_tiff(root / "SEMData" / name / f"{frame:02d}.tif",
                               img.sem_image(x, image_size, rng),
                               img.SEM_PIXELS_PER_MICRON, "DemoSEM 5 kV SE")
            (root / "TEMData" / name / "note.txt").write_text(
                f"{name}: bright-field TEM, nominal x_Au = {x:.2f}\n")

        if with_tomography and mat.measured("tomo", index):
            folder = root / "TomoData" / name
            folder.mkdir(parents=True, exist_ok=True)
            np.save(folder / "tomogram.npy", img.tomo_volume(x, tomo_size, rng))
            (folder / "note.txt").write_text(
                f"reconstructed tomogram, {img.TOMO_NM_PER_VOXEL:.0f} nm voxels\n")

        synthesis[name] = _synthesis_record(index, x)
        characterization[name] = _characterization_record(index, x, paths, n_frames)
        testing[name] = _testing_record(index, x, electro)
        computation[name] = _computation_record(index, x, pdos_path)

    if include_failed_run:
        failed = mat.sample_id(len(fractions) + 1)
        synthesis[failed] = _failed_record(failed, len(fractions) + 1)

    meta = root / "MetaData"
    meta.mkdir(exist_ok=True)
    _write_metadata(meta / "Synthesis_dict.py", "Synthesis_dict",
                    "Colloidal Cu-Au alloy syntheses.", synthesis)
    _write_metadata(meta / "Characterization_dict.py", "Characterization_dict",
                    "Structural, compositional and spectroscopic characterization.",
                    characterization)
    _write_metadata(meta / "Testing_dict.py", "Testing_dict",
                    "CO2-reduction, hydrogen- and oxygen-evolution testing.",
                    testing)
    _write_metadata(meta / "Computation_dict.py", "Computation_dict",
                    "Density-functional calculations on the matching surfaces.",
                    computation)

    (root / "README.txt").write_text(_README)
    return root


def _failed_record(name: str, index: int) -> Dict[str, Any]:
    """A synthesis that aborted, so the table is not uniformly tidy."""
    record = _synthesis_record(index, 0.5)
    record["sample_id"] = name
    record["synthesis_batch"].update({
        "run_id": f"cuau_run_{index:02d}",
        "status": "error",
        "aborted": True,
        "error": "heater interlock tripped at t = 420 s; batch discarded",
        "run_time_s": 420.0,
    })
    return record


_README = """\
NanoOrganizer multimodal demo project
=====================================

A synthetic Cu-Au alloy nanocatalyst library for CO2 electroreduction, seen by
fifteen techniques.  Everything in it is generated from one hidden number per
sample - the gold atomic fraction - so the measurements can be checked against
each other and against the truth.

    from NanoOrganizer import open_project
    wb = open_project(".")
    print(wb.summary())

    from NanoOrganizer.demo import showcase_truth
    showcase_truth()      # what the generator actually used

Layout
------
MetaData/           authored records; four stages, one file each
RawSpectra/         UV-Vis growth series, one .npy per frame
Spectroscopy/       EDS, XPS, Raman, IR, XAS
Scattering/         SAXS and WAXS curves, plus 2D detector images
Dynamics/           XPCS correlation functions
Electrochemistry/   LSVs and product Faradaic efficiencies
Computation/        DFT projected density of states
TEMData/ SEMData/ TomoData/ DLSData/
                    folders picked up by the <Modality>Data/<SampleID>/ rule,
                    with no metadata entry at all

Regenerate or delete it freely - nothing here is source.
"""


__all__ = ["build_showcase_project", "CAMPAIGN", "MARKER"]
